### ISSUE TITLE
Dear marmot !

### ISSUE THREAD

**Issue by JeT76-ESCP** [marmotghost/tikz-3dtools#12]
My apologies for cluttering your Git with my message, but you've moved away from LaTeX sites. 
I truly enjoyed comprehending the ideas that originated from your mind through your responses. 
I just wanted to take a moment to express my gratitude for your assistance when I began coding four years ago. 
I now have thousands of lines of code that were inspired by your answers. 
Your mindmaps have become integral part of my courses. 
It took me quite some time to grasp the potency of certain of the code snippets you shared
My students have also greatly appreciated them. 
A heartfelt thank you!

**Comment by marmotghost** [comment]
Thank you for the kind words!
