### ISSUE TITLE
Can 3dtools draw sierpinski 3D?

### ISSUE THREAD

**Issue by minhthien2016** [marmotghost/tikz-3dtools#13]
I use Mathematica to draw, e.g MengerMesh[3, 3], I get 
![image](https://github.com/marmotghost/tikz-3dtools/assets/55286040/669b6594-d24d-474f-8683-4d95289186c0)

Can 3dtools draw sierpinski 3D?

**Comment by marmotghost** [comment]
In principle it is but I do not think that it will be anywhere as convenient as with Mathematica. The library is, at best, a tool allowing users to write LaTeX codes that allow one to generate things of this sort, but it won't contain routines for such rather special tasks.
