### ISSUE TITLE
Incompatibility with tikzmark

### ISSUE THREAD

**Issue by beurnonmaths** [marmotghost/tikz-3dtools#14]
I think that 3dtools introduces an incompatibility with tikzmark.
The code below compiles fine :

`\documentclass{standalone}
\usepackage{tikz}
%\usetikzlibrary{3dtools} % uncomment and get an error
\usetikzlibrary{tikzmark}

\begin{document}
Hello World \tikzmark{a}
\end{document}`

But if we add tikz-3dtools  library, we get the following error : "_Use of \tikz@ doesn't match its definition_".

Could you investigate, please ?

**Comment by marmotghost** [comment]
Thank you so much for your comment! And sorry for the delay, I am checking this repository less than I probably should. I believe to have fixed the bug, it was something really stupid. (I am not sure if I understand why the bug only appeared in the conjunction with tikzmark, but for now at least your sample document runs through.)

**Comment by beurnonmaths** [comment]
Thanks a lot!
I've just run a few quick tests and, now, everything seems to be working perfectly.

By the way, many thanks for your very useful package.
